name: Deploy OpenTofu Infrastructure

on:
  push:
    branches: [main]
    paths:
        - .github/workflows/deploy-infra-changes.yml
        - infra/**

permissions:
  contents: read

jobs:
    deploy-infra-changes:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
    
        - name: Set up OpenTofu
          uses: opentofu/setup-opentofu@v2 
    
        - name: OpenTofu fmt
          id: fmt
          run: tofu fmt -check
          continue-on-error: true

        - name: Initialize OpenTofu
          run: |
            opentofu init infra
    
        - name: Validate OpenTofu configuration
          run: |
            opentofu validate infra
    
        - name: Plan OpenTofu changes
          run: |
            opentofu plan infra
    
        - name: Apply OpenTofu changes
          run: |
            opentofu apply -auto-approve infra